// import 'package:restaurant_menu/models/menu_item.dart';

// class MenuRepository {
//   List<MenuItem> fetchMenuItems() {
//     return [
//       MenuItem(
//         name: 'Burger',
//         description: 'Delicious beef burger',
//         price: 5.99,
//         imageUrl: 'https://dummyimage.com/300x200/000/fff',
//         category:  'Fast Food',
//       ),
//       MenuItem(
//         name: 'Pizza',
//         description: 'Cheesy pizza with toppings',
//         price: 8.99,
//         imageUrl: 'https://dummyimage.com/400x300/00ff00/000',
//         category:  'Fast Food',
//       ),
//       MenuItem(
//         name: 'Pasta',
//         description: 'Italian pasta with sauce',
//         price: 7.99,
//         imageUrl: 'https://dummyimage.com/600x400/0000ff/fff',
//         category:  'Fast Food',
//       ),
//       MenuItem(
//         name: 'Salad',
//         description: 'Fresh garden salad',
//         price: 4.99,
//         imageUrl: 'https://dummyimage.com/800x600/ff0000/fff',
//         category:  'Healthy Food',
//       ),
//       MenuItem(
//         name: 'Soup',
//         description: 'Hot vegetable soup',
//         price: 3.99,
//         imageUrl: 'https://dummyimage.com/200x200/ff00ff/fff',
//         category:  'Healthy Food',
//       ),
//       MenuItem(
//         name: 'Steak',
//         description: 'Juicy grilled steak',
//         price: 12.99,
//         imageUrl: 'https://dummyimage.com/500x300/ffff00/000',
//         category:  'Healthy Food',
//       ),
//       MenuItem(
//         name: 'Sandwich',
//         description: 'Tasty ham sandwich',
//         price: 5.49,
//         imageUrl: 'https://dummyimage.com/700x500/ff6600/fff',
//         category:  'Fast Food',
//       ),
//       MenuItem(
//         name: 'Fries',
//         description: 'Crispy french fries',
//         price: 2.99,
//         imageUrl: 'https://dummyimage.com/900x700/663399/fff',
//         category:  'Fast Food',
//       ),
//       MenuItem(
//         name: 'Ice Cream',
//         description: 'Creamy ice cream',
//         price: 3.49,
//         imageUrl: 'https://dummyimage.com/250x150/9966cc/fff',
//         category:  'Dessert',
//       ),
//       MenuItem(
//         name: 'Cake',
//         description: 'Chocolate cake',
//         price: 4.49,
//         imageUrl: 'https://dummyimage.com/450x350/00cccc/000',
//         category:  'Dessert',
//       ),
//       MenuItem(
//         name: 'Coffee',
//         description: 'Hot brewed coffee',
//         price: 1.99,
//         imageUrl: 'https://dummyimage.com/650x450/cc00cc/fff',
//         category:  'Beverage',
//       ),
//       MenuItem(
//         name: 'Tea',
//         description: 'Refreshing tea',
//         price: 1.49,
//         imageUrl: 'https://dummyimage.com/850x650/339966/fff',
//         category:  'Beverage',
//       ),
//       MenuItem(
//         name: 'Muffin',
//         description: 'Tasty muffin',
//         price: 2.99,
//         imageUrl: 'https://dummyimage.com/150x100/ff9933/000',
//         category:  'Dessert',
//       ),
//       MenuItem(
//         name: 'Waffles',
//         description: 'Delicious waffles',
//         price: 6.99,
//         imageUrl: 'https://dummyimage.com/350x250/33cc99/fff',
//         category:  'Dessert',
//       ),
//       MenuItem(
//         name: 'Pancakes',
//         description: 'Fluffy pancakes',
//         price: 4.99,
//         imageUrl: 'https://dummyimage.com/550x350/3399ff/000',
//         category:  'Dessert',
//       ),
//       MenuItem(
//         name: 'Bacon',
//         description: 'Crispy bacon',
//         price: 3.49,
//         imageUrl: 'https://dummyimage.com/750x550/996633/fff',
//         category:  'Healthy Food',
//       ),
//       MenuItem(
//         name: 'Omelette',
//         description: 'Cheese omelette',
//         price: 5.99,
//         imageUrl: 'https://dummyimage.com/950x750/cc9966/fff',
//         category:  'Healthy Food',
//       ),
//       MenuItem(
//         name: 'Smoothie',
//         description: 'Fruit smoothie',
//         price: 4.49,
//         imageUrl: 'https://dummyimage.com/100x100/6699cc/000',
//         category:  'Beverage',
//       ),
//       MenuItem(
//         name: 'Milkshake',
//         description: 'Chocolate milkshake',
//         price: 4.99,
//         imageUrl: 'https://dummyimage.com/300x250/663366/fff',
//         category:  'Beverage',
//       ),
//       MenuItem(
//         name: 'Latte',
//         description: 'Hot latte',
//         price: 3.99,
//         imageUrl: 'https://dummyimage.com/500x400/ff6699/000',
//         category:  'Beverage',
//       ),
//     ];
//   }
// }
